create smoke-test job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -436,28 +436,65 @@ jobs:
           event: fail
           template: basic_fail_1
 
-#  smoke-test:
-#    docker:
+  smoke-test:
+    docker:
       # Lightweight Docker image 
-#    steps:
+      - image: cimg/aws:2022.06
+    steps:
       # Checkout code from git
-#      - run:
-#          name: Install dependencies
-#          command: |
+      - checkout
+      - attach_workspace:
+            at: ~/
+      - run:
+          name: Install dependencies
+          command: |
             # your code here
-#      - run:
-#          name: Get backend url
-#          command: |
+            sudo apt install curl
+      - run:
+          name: Get backend url
+          command: |
             # your code here
-#      - run:
-#          name: Backend smoke test.
-#          command: |
+            #      - run:
+          name: Backend smoke test.
+          command: |
             # your code here
-#      - run:
-#          name: Frontend smoke test.
-#          command: |
+            export BACKEND_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --region us-east-1 \
+              --output text )
+            echo $BACKEND_IP
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo ${API_URL}
+            if curl ${API_URL}/api/status | grep "ok"
+            then
+                exit 0
+            else
+                exit 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
             # your code here
-      # Here's where you will add some code to rollback on failure  
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+              exit 0
+            else
+              exit 1
+            fi
+            # Here's where you will add some code to rollback on failure  
+      - destroy-environment:
+          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
+          event: on_fail
+      - revert-migrations:
+          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
+      - slack/notify:
+          channel: circleci-udapeople
+          event: fail
+          template: basic_fail_1
+
 
 #  cloudfront-update:
 #    docker:
@@ -526,8 +563,8 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-#      - smoke-test:
-#          requires: [deploy-backend, deploy-frontend]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
 #      - cloudfront-update:
 #          requires: [smoke-test]
 #      - cleanup:
